# Generated by Django 3.0.8 on 2020-09-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='vedios',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
