# Generated by Django 3.0.8 on 2020-09-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_topic_vedios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='vedios',
            new_name='name',
        ),
    ]
