# Generated by Django 3.0.8 on 2020-09-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200908_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=120)),
            ],
        ),
    ]
