# Generated by Django 3.0.8 on 2020-09-12 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200912_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='post',
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='user',
            field=models.CharField(max_length=49),
        ),
    ]
